services:
  postgres:
    image: postgres
    restart: always
    env_file: .env.compose
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55670:55679" # zpages extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
volumes:
  db:
